version: '3.8'

services:
  folder-creator:
    build:
      context: .
    container_name: folder-creator
    volumes:
      - shared_volume:/shared
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

volumes:
  shared_volume:
    external: true
# run this to create the volume : docker volume create shared_volume
