services:
  folder-creator:
    build:
      context: .
    container_name: folder-creator-ogws80088okoww4cg4w8wso0-105519732674
    volumes:
      - 'shared_volume:/shared'
    ports:
      - '3000:3000'
    environment:
      COOLIFY_URL: 'http://folder-raw.sgcyemen.com'
      COOLIFY_FQDN: folder-raw.sgcyemen.com
    restart: unless-stopped
    labels:
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=http://folder-raw.sgcyemen.com'
 
    networks:
      ogws80088okoww4cg4w8wso0: null
volumes:
  shared_volume:
    external: true
  networks:
  ogws80088okoww4cg4w8wso0:
    name: ogws80088okoww4cg4w8wso0
    external: true
configs: {  }
secrets: {  }
