services:
  folder-creator:
    build:
      context: .
    container_name: folder-creator
    volumes:
      - 'shared_volume:/shared'
    ports:
      - '3000:3000'
    environment:
      COOLIFY_URL: 'http://folder-raw.sgcyemen.com'
      COOLIFY_FQDN: folder-raw.sgcyemen.com
    restart: unless-stopped
    labels:
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=http://folder-raw.sgcyemen.com'
volumes:
  shared_volume:
    external: true

configs: {  }
secrets: {  }
